services:
  postgres:
    image: postgres:15
    container_name: mds_db
    environment:
      POSTGRES_PASSWORD: mfiddb
      POSTGRES_USER: mfi
      POSTGRES_DB: mds
    ports:
      - "5432:5432"     
    # volumes:
      # - ./metadata_store-pg/init-mds.sql:/docker-entrypoint-initdb.d/init-mds.sql

  mds_connector:
    build:
      context: ./metadata_store-pg
      dockerfile: Dockerfile
    container_name: mds_connector
    volumes:
      - ./metadata_store-pg:/app
    network_mode: host
    working_dir: /app
    depends_on:
      postgres:
        condition: service_started
    command: ["/bin/bash", "/app/docker-entrypoint.sh"]        
    # command: ["/bin/bash", "-c", "tail -f /dev/null"] # Keep the container running for testing