services:
  test_mds_db:
    image: postgres:15
    container_name: test_mds_db
    environment:
      POSTGRES_PASSWORD: mfiddb
      POSTGRES_USER: mfi
      POSTGRES_DB: mds
    ports:
      - "2432:5432"     
    # volumes:
      # - ./metadata_store-pg/init-mds.sql:/docker-entrypoint-initdb.d/init-mds.sql
  
  test_broker:
    image: emqx/emqx-enterprise:6.2.0
    container_name: test_broker
    ports:
      - "2883:1883"
      - "28083:18083"
    healthcheck:
      test: ["CMD-SHELL", "emqx ctl status"]
      interval: 15s
      timeout: 10s
      retries: 3

  test_mds_connector:
    build:
      context: ./metadata_store-pg
      dockerfile: Dockerfile
    container_name: test_mds_connector
    volumes:
      - ./metadata_store-pg:/app
    network_mode: host
    working_dir: /app
    depends_on:
      postgres:
        condition: service_started
      broker:
        condition: service_healthy
    command: ["/bin/bash", "/app/docker-entrypoint.test.sh"]        
    # command: ["/bin/bash", "-c", "tail -f /dev/null"] # Keep the container running for testing