services:
  blob-connector:
    platform: linux/amd64
    build:
      context: ../../mfi_ddb_database_nodes/blob/connector
      dockerfile: Dockerfile
    container_name: mfi-blob-connector
    image: cmumfi/mfi-ddb-blob-connector:latest
    profiles:
      - "blob"
      - "dbn"
    ports:
      - "9465:9464"   # OpenTelemetry Metrics Port for Blob Connector
    command: opentelemetry-instrument --metrics_exporter prometheus python -u connector.py config.yaml
    environment:
      - OTEL_SERVICE_NAME=mfi-blob-connector
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      - OTEL_EXPORTER_PROMETHEUS_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    depends_on:
      mqtt-broker:
        condition: service_started
    volumes:
      - ../.data/blob_storage:/data/blob_storage
      - ./connector-config.yaml:/app/config.yaml:ro
    networks:
      - mfi_network
    restart: always

  blob-dws:
    platform: linux/amd64
    build:
      context: ../../mfi_ddb_database_nodes/blob/dws
      dockerfile: Dockerfile
    container_name: mfi-blob-dws
    image: cmumfi/mfi-ddb-blob-dws:latest
    profiles:
      - "blob"
      - "dbn"
    ports:
      - "50053:50053" # gRPC Port
      - "9466:9464"   # OpenTelemetry Metrics Port for Blob DWS
    command: opentelemetry-instrument --metrics_exporter prometheus python -u server.py
    environment:
      - OTEL_SERVICE_NAME=mfi-blob-dws
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      - OTEL_EXPORTER_PROMETHEUS_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    depends_on:
      - blob-connector
    volumes:
      - ../.data/blob_storage:/data/blob_storage:ro
      - ./dws-config.yaml:/app/config.yaml:ro
    networks:
      - mfi_network
    restart: always