// UI fields mirror the module configuration YAML files; file-qualified keys keep values independent.
export const YAML_CONFIG_BLUEPRINT = {
  "aveva/config.yaml": {
    title: "docker/aveva/config.yaml",
    module: "aveva",
    fields: [
      {"label": "url", "type": "text", "default": "<redacted>", "nullable": false, "key": "aveva/config.yaml::url"},
      {"label": "username", "type": "text", "default": "<redacted>", "nullable": false, "key": "aveva/config.yaml::username"},
      {"label": "password", "type": "password", "default": "<redacted>", "nullable": false, "key": "aveva/config.yaml::password"},
      {"label": "dataserver.name", "type": "text", "default": "<redacted>", "nullable": false, "key": "aveva/config.yaml::dataserver.name"},
      {"label": "dataserver.webid", "type": "text", "default": "<redacted>", "nullable": false, "key": "aveva/config.yaml::dataserver.webid"},
      {"label": "mqtt_connector.path", "type": "text", "default": "<redacted>", "nullable": false, "key": "aveva/config.yaml::mqtt_connector.path"},
    ],
  },
  "blob/connector-config.yaml": {
    title: "docker/blob/connector-config.yaml",
    module: "blob",
    fields: [
      {"label": "mqtt.broker_address", "type": "text", "default": "mfi-mqtt-broker", "nullable": false, "key": "blob/connector-config.yaml::mqtt.broker_address"},
      {"label": "mqtt.broker_port", "type": "number", "default": 1883, "nullable": false, "key": "blob/connector-config.yaml::mqtt.broker_port"},
      {"label": "mqtt.username", "type": "text", "default": "username", "nullable": false, "key": "blob/connector-config.yaml::mqtt.username"},
      {"label": "mqtt.password", "type": "password", "default": "password", "nullable": false, "key": "blob/connector-config.yaml::mqtt.password"},
      {"label": "mqtt.tls_enabled", "type": "boolean", "default": false, "nullable": false, "key": "blob/connector-config.yaml::mqtt.tls_enabled"},
      {"label": "mqtt.debug", "type": "boolean", "default": false, "nullable": false, "key": "blob/connector-config.yaml::mqtt.debug"},
      {"label": "config.save_directory", "type": "text", "default": "/data/blob_storage", "nullable": false, "key": "blob/connector-config.yaml::config.save_directory"},
      {"label": "config.topic.version", "type": "text", "default": "1.0", "nullable": false, "key": "blob/connector-config.yaml::config.topic.version"},
      {"label": "config.topic.topic_family", "type": "text", "default": "blob", "nullable": false, "key": "blob/connector-config.yaml::config.topic.topic_family"},
      {"label": "config.topic.enterprise", "type": "text", "default": "mfi", "nullable": false, "key": "blob/connector-config.yaml::config.topic.enterprise"},
      {"label": "config.topic.site", "type": "text", "default": null, "nullable": true, "key": "blob/connector-config.yaml::config.topic.site"},
      {"label": "config.topic.area", "type": "text", "default": null, "nullable": true, "key": "blob/connector-config.yaml::config.topic.area"},
      {"label": "config.topic.device", "type": "text", "default": null, "nullable": true, "key": "blob/connector-config.yaml::config.topic.device"},
    ],
  },
  "blob/dws-config.yaml": {
    title: "docker/blob/dws-config.yaml",
    module: "blob",
    fields: [
      {"label": "config.blob_dir", "type": "text", "default": "/data/blob_storage", "nullable": false, "key": "blob/dws-config.yaml::config.blob_dir"},
      {"label": "config.index_path", "type": "text", "default": "/data/blob_storage/index.jsonl", "nullable": false, "key": "blob/dws-config.yaml::config.index_path"},
    ],
  },
  "kv-psql/connector-config.yaml": {
    title: "docker/kv-psql/connector-config.yaml",
    module: "kv",
    fields: [
      {"label": "mqtt.broker", "type": "text", "default": "mqtt-broker", "nullable": false, "key": "kv-psql/connector-config.yaml::mqtt.broker"},
      {"label": "mqtt.port", "type": "number", "default": 1883, "nullable": false, "key": "kv-psql/connector-config.yaml::mqtt.port"},
      {"label": "mqtt.client_id", "type": "text", "default": "kv-psql-connector", "nullable": false, "key": "kv-psql/connector-config.yaml::mqtt.client_id"},
      {"label": "mqtt.topics", "type": "list", "default": ["mfi-v1.0-kv/#"], "nullable": false, "key": "kv-psql/connector-config.yaml::mqtt.topics"},
      {"label": "postgres.host", "type": "text", "default": "kv-psql-db", "nullable": false, "key": "kv-psql/connector-config.yaml::postgres.host"},
      {"label": "postgres.port", "type": "number", "default": 5432, "nullable": false, "key": "kv-psql/connector-config.yaml::postgres.port"},
      {"label": "postgres.database", "type": "text", "default": "mfi_kv", "nullable": false, "key": "kv-psql/connector-config.yaml::postgres.database"},
      {"label": "postgres.user", "type": "text", "default": "mfi", "nullable": false, "key": "kv-psql/connector-config.yaml::postgres.user"},
      {"label": "postgres.password", "type": "password", "default": "mfiddb", "nullable": false, "key": "kv-psql/connector-config.yaml::postgres.password"},
    ],
  },
  "kv-psql/dws-config.yaml": {
    title: "docker/kv-psql/dws-config.yaml",
    module: "kv",
    fields: [
      {"label": "postgres.host", "type": "text", "default": "kv-psql-db", "nullable": false, "key": "kv-psql/dws-config.yaml::postgres.host"},
      {"label": "postgres.port", "type": "number", "default": 5432, "nullable": false, "key": "kv-psql/dws-config.yaml::postgres.port"},
      {"label": "postgres.database", "type": "text", "default": "mfi_kv", "nullable": false, "key": "kv-psql/dws-config.yaml::postgres.database"},
      {"label": "postgres.user", "type": "text", "default": "mfi", "nullable": false, "key": "kv-psql/dws-config.yaml::postgres.user"},
      {"label": "postgres.password", "type": "password", "default": "mfiddb", "nullable": false, "key": "kv-psql/dws-config.yaml::postgres.password"},
      {"label": "dws.port", "type": "number", "default": 50051, "nullable": false, "key": "kv-psql/dws-config.yaml::dws.port"},
    ],
  },
  "metadata-rws/rws-dws-endpoints.yaml": {
    title: "docker/metadata-rws/rws-dws-endpoints.yaml",
    module: "rws",
    fields: [
      {"label": "services.metadata_service.url", "type": "text", "default": "http://mfi-metadata-store-db:5432", "nullable": false, "key": "metadata-rws/rws-dws-endpoints.yaml::services.metadata_service.url"},
      {"label": "services.metadata_service.topic_families", "type": "list", "default": ["mfi-v1.0-kv"], "nullable": false, "key": "metadata-rws/rws-dws-endpoints.yaml::services.metadata_service.topic_families"},
      {"label": "services.kv_service.url", "type": "text", "default": "http://mfi-kv-psql-dws:50051", "nullable": false, "key": "metadata-rws/rws-dws-endpoints.yaml::services.kv_service.url"},
      {"label": "services.kv_service.topic_families", "type": "list", "default": ["mfi-v1.0-kv"], "nullable": false, "key": "metadata-rws/rws-dws-endpoints.yaml::services.kv_service.topic_families"},
      {"label": "services.historian_service.url", "type": "text", "default": "http://mfi-timescaledb-dws:50051", "nullable": false, "key": "metadata-rws/rws-dws-endpoints.yaml::services.historian_service.url"},
      {"label": "services.historian_service.topic_families", "type": "list", "default": ["mfi-v1.0-historian"], "nullable": false, "key": "metadata-rws/rws-dws-endpoints.yaml::services.historian_service.topic_families"},
      {"label": "services.cfs_service.url", "type": "text", "default": "http://blob-dws:50051", "nullable": false, "key": "metadata-rws/rws-dws-endpoints.yaml::services.cfs_service.url"},
      {"label": "services.cfs_service.topic_families", "type": "list", "default": ["mfi-v1.0-blob"], "nullable": false, "key": "metadata-rws/rws-dws-endpoints.yaml::services.cfs_service.topic_families"},
    ],
  },
  "timescale/connector-config.yaml": {
    title: "docker/timescale/connector-config.yaml",
    module: "ts",
    fields: [
      {"label": "mqtt.broker_address", "type": "text", "default": "mqtt-broker", "nullable": false, "key": "timescale/connector-config.yaml::mqtt.broker_address"},
      {"label": "mqtt.broker_port", "type": "number", "default": 1883, "nullable": false, "key": "timescale/connector-config.yaml::mqtt.broker_port"},
      {"label": "mqtt.topic", "type": "text", "default": "mfi-v1.0-historian/#", "nullable": false, "key": "timescale/connector-config.yaml::mqtt.topic"},
      {"label": "mqtt.username", "type": "text", "default": "", "nullable": false, "key": "timescale/connector-config.yaml::mqtt.username"},
      {"label": "mqtt.password", "type": "password", "default": "", "nullable": false, "key": "timescale/connector-config.yaml::mqtt.password"},
      {"label": "timescaledb.host", "type": "text", "default": "timescaledb-db", "nullable": false, "key": "timescale/connector-config.yaml::timescaledb.host"},
      {"label": "timescaledb.port", "type": "number", "default": 5432, "nullable": false, "key": "timescale/connector-config.yaml::timescaledb.port"},
      {"label": "timescaledb.user", "type": "text", "default": "tsdb", "nullable": false, "key": "timescale/connector-config.yaml::timescaledb.user"},
      {"label": "timescaledb.password", "type": "password", "default": "timescale", "nullable": false, "key": "timescale/connector-config.yaml::timescaledb.password"},
      {"label": "timescaledb.dbname", "type": "text", "default": "ddb_ts", "nullable": false, "key": "timescale/connector-config.yaml::timescaledb.dbname"},
      {"label": "component_id", "type": "text", "default": "default_component", "nullable": false, "key": "timescale/connector-config.yaml::component_id"},
    ],
  },
  "timescale/dws-config.yaml": {
    title: "docker/timescale/dws-config.yaml",
    module: "ts",
    fields: [
      {"label": "timescaledb.host", "type": "text", "default": "timescaledb-db", "nullable": false, "key": "timescale/dws-config.yaml::timescaledb.host"},
      {"label": "timescaledb.port", "type": "number", "default": 5432, "nullable": false, "key": "timescale/dws-config.yaml::timescaledb.port"},
      {"label": "timescaledb.user", "type": "text", "default": "tsdb", "nullable": false, "key": "timescale/dws-config.yaml::timescaledb.user"},
      {"label": "timescaledb.password", "type": "password", "default": "timescale", "nullable": false, "key": "timescale/dws-config.yaml::timescaledb.password"},
      {"label": "timescaledb.dbname", "type": "text", "default": "ddb_ts", "nullable": false, "key": "timescale/dws-config.yaml::timescaledb.dbname"},
    ],
  },
};
