watch_dir: List of directories to watch for new files.The first directory is used
  to create a starter file.
buffer_size: Maximum number of files to buffer before streaming. First in first out.
wait_before_read: Time in seconds to wait to ensure that a new file is fully written.
system:
  name: Name of the system
  trial_id: Trial ID for the system. No spaces or special characters allowed.
  description: Description of the system
  other_attributes: Other attributes of the system
