trial_id: Trial ID for the ROS device. No spaces or special characters allowed.
devices: 'List of devices to subscribe. Required keys: [''namespace'', ''rostopics''].''attributes''
  are optional. Use it to add attributes of the device.'
