trial_id: Trial ID for the ROS device. No spaces or special characters allowed.
set_ros_callback: Set ROS callback to receive data from ROS topics. (default=True).
devices: 'List of devices to subscribe. Required keys: [''namespace'', ''rostopics''].''attributes''
  are optional. Use it to add attributes of the device.'
