[mqtt]
broker_address=localhost
broker_port=2883

[topic]
topic_family=kv
version=1.0
enterprise=CMU

; Following keys are optional. 
; Uncomment and fill them if you want to use them in the topic name

; site=Machine Shop