services:
  blob-connector:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: src/mfi_ddb/databases/blob/connector/Dockerfile
    container_name: mfi-blob-connector
    image: cmumfi/mfi-ddb-blob-connector:latest
    depends_on:
      mqtt-broker:
        condition: service_started
    volumes:
      - blob_storage:/data/blob_storage
    networks:
      - mfi_network
    restart: on-failure

  blob-dws:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: src/mfi_ddb/databases/blob/dws/Dockerfile
    container_name: mfi-blob-dws
    image: cmumfi/mfi-ddb-blob-dws:latest
    ports:
      - "50053:50053"
    depends_on:
      - blob-connector
    volumes:
      - blob_storage:/data/blob_storage:ro
    networks:
      - mfi_network
    restart: always