services:
  timescaledb-db:
    platform: linux/amd64
    image: timescale/timescaledb:latest-pg16
    container_name: mfi-timescaledb-db
    environment:
      - POSTGRES_USER=tsdb
      - POSTGRES_PASSWORD=timescale
      - POSTGRES_DB=ddb_ts
    ports:
      - "5432:5432"
    volumes:
      - timescale_storage:/var/lib/postgresql/data
      - ../src/mfi_ddb/databases/timescaledb/init_schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
    networks:
      - mfi_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tsdb -d ddb_ts"]
      interval: 5s
      timeout: 5s
      retries: 5

  timescaledb-connector:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: src/mfi_ddb/databases/timescaledb/connector/Dockerfile
    container_name: mfi-timescaledb-connector
    image: cmumfi/mfi-ddb-timescaledb-connector:latest
    depends_on:
      mqtt-broker:
        condition: service_started
      timescaledb-db:
        condition: service_healthy
    volumes:
      - ../src/mfi_ddb/databases/timescaledb/connector/config.yaml:/app/config.yaml:ro
    networks:
      - mfi_network
    restart: on-failure

  timescaledb-dws:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: src/mfi_ddb/databases/timescaledb/dws/Dockerfile
    container_name: mfi-timescaledb-dws
    ports:
      - "50052:50052"
    depends_on:
      timescaledb-db:
        condition: service_healthy
    networks:
      - mfi_network
    image: cmumfi/mfi-ddb-timescaledb-dws:latest
    restart: always