services:
  kv-psql-db:
    platform: linux/amd64
    image: postgres:15-alpine
    container_name: mfi-kv-psql-db
    environment:
      - POSTGRES_USER=mfi
      - POSTGRES_PASSWORD=mfiddb
      - POSTGRES_DB=mfi_kv
    ports:
      - "5431:5432"
    volumes:
      - kv_psql_storage:/var/lib/postgresql/data
    networks:
      - mfi_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mfi -d mfi_kv"]
      interval: 5s
      timeout: 5s
      retries: 5

  kv-psql-connector:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: src/mfi_ddb/databases/kv-psql/connector/Dockerfile
    container_name: mfi-kv-psql-connector
    depends_on:
      mqtt-broker:
        condition: service_started
      kv-psql-db:
        condition: service_healthy
    networks:
      - mfi_network
    volumes:
      - ../src/mfi_ddb/databases/kv-psql/connector/config.yaml:/app/config.yaml:ro
    restart: on-failure

  kv-psql-dws:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: src/mfi_ddb/databases/kv-psql/dws/Dockerfile
    container_name: mfi-kv-psql-dws
    ports:
      - "50051:50051"
    command: >
      sh -c "python -m mfi_ddb.databases.kv-psql.dws.init_db && 
             python -m mfi_ddb.databases.kv-psql.dws.server"
    depends_on:
      kv-psql-db:
        condition: service_healthy
    networks:
      - mfi_network
    restart: always