networks:
  mfi_network:
    driver: bridge

volumes:
  timescale_storage:
  kv_psql_storage:
  blob_storage:
  mds_storage:
  emqx_data:
  emqx_log:

include:
  - path: kv-sql/compose.yaml
  - path: timescale/compose.yaml
  - path: retrieval-api/compose.yaml
  - path: blob/compose.yaml

services:
  # SHARED INFRASTRUCTURE
  mqtt-broker:
    image: emqx/emqx:5.8.0
    container_name: mfi-mqtt-broker
    ports:
      - "1883:1883"     # MQTT TCP port
      - "8083:8083"     # MQTT websockets port
      - "18083:18083"   # EMQX dashboard UI
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    environment:
      - EMQX_NAME=mfi_broker
    networks:
      - mfi_network
    restart: always