FROM python:3.12-slim

RUN pip install uv

RUN mkdir /app
WORKDIR /app

COPY ./backend ./api

RUN apt-get update && apt-get install -y git
RUN git clone --recurse-submodules https://github.com/cmu-mfi/mfi_ddb_library.git mfi_ddb

RUN uv pip install --system ./mfi_ddb
RUN uv pip install --system fastapi[all]

WORKDIR /app/api

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]