services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1 # Use a recent stable version
    container_name: cadvisor
    # Necessary for Apple Silicon Macs:
    platform: linux/amd64 
    ports:
      - "8080:8080"
    volumes:
    # doesn't store any state so using docker volumes, it will store it in prometheus's db
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - mfi_network
    devices:
      - /dev/kmsg
    restart: unless-stopped
    security_opt:
      - label=disable # Prevents SELinux permission issues if testing on Linux VMs later
  
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: mfi-prometheus
    ports:
      - "9090:9090"
    volumes:
      # Relative to this compose file's folder location
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../.data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - mfi_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.1 # Clean, stable OSS build
    container_name: mfi-grafana
    ports:
      - "3005:3000"
    volumes:
      # Automatically provision the Prometheus database connection
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      # Persist dashboard edits and user profiles locally
      - ../.data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - mfi_network
    restart: unless-stopped