[mqtt]
address=test.mosquitto.org
port=1883
username=mqtt_user
password=mqtt_password
tls_enabled=false

[topic]
topic_family=kv
version=1.0
enterprise=CMU

; Following keys are optional. 
; Uncomment and fill them if you want to use them in the topic name

; site=Machine Shop