watch_dir: List of directories to watch for new files. The first directory will be
  used to create a starter file.
buffer_size: Maximum number of files to buffer before streaming. If the buffer is
  full, the oldest file will be removed.
wait_before_read: Time in seconds to wait before reading a new file after it is created.
  This is to ensure the file is fully written.
system:
  name: Name of the system
  trial_id: Trial ID for the system. No spaces or special characters allowed.
  description: Description of the system
  other_attributes: Other attributes of the system
