mqtt:
  broker_address: mqtt.example.com
  broker_port: 1883
trial_id: trial_001
queue_size: 10
topics:
- component_id: robot-arm-1
  topic: robot-arm/1/data
  trial_id: trial_001
- component_id: machine-a
  topic: machine/a/data
