# Use reference: https://www.docker.com/blog/how-to-dockerize-react-app/

FROM node:22-alpine


WORKDIR /app

COPY ./frontend_app ./

RUN npm install
# ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]