trial_id: Trial ID for the ROS device. No spaces or special characters allowed.
set_ros_callback: Set ROS callback to receive data from ROS topics. If set to False,
  you need to call get_data() method to get data from ROS topics.
devices: List of devices to subscribe to. Each device should have a 'namespace' and
  a list of 'rostopics' to subscribe to. 'attributes' are optional and can be used
  to set the attributes of the device.
