services:
  aveva-pi-dws:
    platform: linux/amd64
    build:
      context: ../../mfi_ddb_database_nodes/aveva-pi/dws
      dockerfile: Dockerfile
      tags:
        - cmumfi/mfi-ddb-aveva-pi-dws:${VERSION:-latest}
        - cmumfi/mfi-ddb-aveva-pi-dws:latest
    container_name: mfi-aveva-pi-dws
    image: cmumfi/mfi-ddb-aveva-pi-dws:${VERSION:-latest}
    profiles:
      - "aveva"
      - "dbn"
    ports:
      - "50054:50054"
    networks:
      - mfi_network
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    restart: always
