services:
  aveva-pi-dws:
    platform: linux/amd64
    build:
      context: ../../mfi_ddb_database_nodes/aveva-pi/dws
      dockerfile: Dockerfile
    container_name: mfi-aveva-pi-dws
    image: cmumfi/mfi-ddb-aveva-pi-dws:latest
    profiles:
      - "aveva"
      - "dbn"
    ports:
      - "50054:50054" # Adjust your host-facing port choice if needed
      - "9464:9464"   # OpenTelemetry Prometheus Metrics Port
    command: opentelemetry-instrument python server.py
    environment:
      - OTEL_SERVICE_NAME=mfi-aveva-pi-dws
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      - OTEL_EXPORTER_PROMETHEUS_HOST=0.0.0.0
    networks:
      - mfi_network
    volumes:
      # Inject configurations directly into the container's working directory root
      - ./config.yaml:/app/config.yaml:ro
    restart: always